menu:
  home: / || home                          //首页
  archives: /archives/ || archive          //归档
  categories: /categories/ || th           //分类
  tags: /tags/ || tags                     //标签
  #about: /about/ || user                   //关于
  #schedule: /schedule/ || calendar        //日程表
  #sitemap: /sitemap.xml || sitemap        //站点地图
  #commonweal: /404/ || heartbeat          //公益404

# Schemes
# scheme: Muse
scheme: Mist
# scheme: Pisces
# scheme: Gemini

# Sidebar Avatar
avatar: https://gitee.com/littlefxc/oss/raw/master/images/鸣人向日葵.jpg

rss: /atom.xml

toc:
  enable: true
  number: false
  wrap: false

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true